### ISSUE TITLE
Admin add product not working!

### ISSUE THREAD

**Issue by kiplangatbryan** [samuelmaina/online-shop#15]
TypeError: req.csrfToken is not a function
    at errorHandlerMiddleware (C:\Users\bryan\Documents\Fix-Issues\online-shop\appMiddlewares\errorHandler.js:5:32)
    at Layer.handle_error (C:\Users\bryan\Documents\Fix-Issues\online-shop\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Users\bryan\Documents\Fix-Issues\online-shop\node_modules\express\lib\router\index.js:315:13)
    at C:\Users\bryan\Documents\Fix-Issues\online-shop\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\bryan\Documents\Fix-Issues\online-shop\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\bryan\Documents\Fix-Issues\online-shop\node_modules\express\lib\router\index.js:275:10)
    at Layer.handle_error (C:\Users\bryan\Documents\Fix-Issues\online-shop\node_modules\express\lib\router\layer.js:67:12)
    at trim_prefix (C:\Users\bryan\Documents\Fix-Issues\online-shop\node_modules\express\lib\router\index.js:315:13)
    at C:\Users\bryan\Documents\Fix-Issues\online-shop\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\bryan\Documents\Fix-Issues\online-shop\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\bryan\Documents\Fix-Issues\online-shop\node_modules\express\lib\router\index.js:275:10)
    at Layer.handle_error (C:\Users\bryan\Documents\Fix-Issues\online-shop\node_modules\express\lib\router\layer.js:67:12)
    at trim_prefix (C:\Users\bryan\Documents\Fix-Issues\online-shop\node_modules\express\lib\router\index.js:315:13)
    at C:\Users\bryan\Documents\Fix-Issues\online-shop\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\bryan\Documents\Fix-Issues\online-shop\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\bryan\Documents\Fix-Issues\online-shop\node_modules\express\lib\router\index.js:275:10)

**Comment by samuelmaina** [comment]
pull the latest code. I have tried on my side and everything is working just fine. Try that, if not, get back to me.
